from __future__ import annotations

__all__ = (
    "And",
    "AndFilter",
    "Contains",
    "ContainsAny",
    "ContainsAnyFilter",
    "ContainsFilter",
    "EndsWith",
    "EndsWithAny",
    "EndsWithAnyFilter",
    "EndsWithFilter",
    "Equals",
    "EqualsAny",
    "EqualsAnyFilter",
    "EqualsFilter",
    "Filter",
    "FilterDict",
    "Glob",
    "GlobFilter",
    "LogicalChildFilterDict",
    "LogicalChildrenFilterDict",
    "LogicalFilter",
    "MultiPatternFilter",
    "MultiPatternFilterDict",
    "Not",
    "NotFilter",
    "Or",
    "OrFilter",
    "PatternFilter",
    "PatternFilterDict",
    "Regex",
    "RegexFilter",
    "StartsWith",
    "StartsWithAny",
    "StartsWithAnyFilter",
    "StartsWithFilter",
    "register_filter",
)

from kaparoo.filesystem.search.filters.base import Filter
from kaparoo.filesystem.search.filters.logical import (
    And,
    AndFilter,
    LogicalFilter,
    Not,
    NotFilter,
    Or,
    OrFilter,
)
from kaparoo.filesystem.search.filters.multi_pattern import (
    ContainsAny,
    ContainsAnyFilter,
    EndsWithAny,
    EndsWithAnyFilter,
    EqualsAny,
    EqualsAnyFilter,
    MultiPatternFilter,
    StartsWithAny,
    StartsWithAnyFilter,
)
from kaparoo.filesystem.search.filters.pattern import (
    Contains,
    ContainsFilter,
    EndsWith,
    EndsWithFilter,
    Equals,
    EqualsFilter,
    Glob,
    GlobFilter,
    PatternFilter,
    Regex,
    RegexFilter,
    StartsWith,
    StartsWithFilter,
)
from kaparoo.filesystem.search.filters.typed import (
    FilterDict,
    LogicalChildFilterDict,
    LogicalChildrenFilterDict,
    MultiPatternFilterDict,
    PatternFilterDict,
)
from kaparoo.filesystem.search.filters.utils import register_filter
